# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'auctionUi.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QGroupBox, QLabel,
    QLineEdit, QListWidget, QListWidgetItem, QMainWindow,
    QPushButton, QSizePolicy, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(634, 903)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.lbUrl = QLabel(self.centralwidget)
        self.lbUrl.setObjectName(u"lbUrl")
        self.lbUrl.setGeometry(QRect(15, 50, 91, 31))
        font = QFont()
        font.setFamilies([u"HY\uacac\uace0\ub515"])
        font.setPointSize(12)
        font.setBold(False)
        self.lbUrl.setFont(font)
        self.lbUrl.setLineWidth(3)
        self.linUrl = QLineEdit(self.centralwidget)
        self.linUrl.setObjectName(u"linUrl")
        self.linUrl.setGeometry(QRect(110, 51, 511, 31))
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(15, 116, 251, 91))
        font1 = QFont()
        font1.setFamilies([u"\ub9d1\uc740 \uace0\ub515"])
        font1.setPointSize(10)
        font1.setBold(True)
        self.groupBox.setFont(font1)
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(23, 22, 71, 21))
        self.linMaxPrice = QLineEdit(self.groupBox)
        self.linMaxPrice.setObjectName(u"linMaxPrice")
        self.linMaxPrice.setGeometry(QRect(104, 23, 113, 22))
        self.linAdditionalPrice = QLineEdit(self.groupBox)
        self.linAdditionalPrice.setObjectName(u"linAdditionalPrice")
        self.linAdditionalPrice.setGeometry(QRect(104, 53, 113, 22))
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(23, 53, 71, 21))
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(270, 328, 351, 241))
        font2 = QFont()
        font2.setPointSize(10)
        font2.setBold(True)
        self.groupBox_2.setFont(font2)
        self.label_4 = QLabel(self.groupBox_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(5, 60, 71, 21))
        self.oneWindow = QLineEdit(self.groupBox_2)
        self.oneWindow.setObjectName(u"oneWindow")
        self.oneWindow.setGeometry(QRect(76, 51, 261, 41))
        font3 = QFont()
        font3.setPointSize(17)
        font3.setBold(True)
        self.oneWindow.setFont(font3)
        self.btnStart = QPushButton(self.groupBox_2)
        self.btnStart.setObjectName(u"btnStart")
        self.btnStart.setGeometry(QRect(228, 128, 111, 61))
        self.btnStart.setFont(font2)
        self.btnCancel = QPushButton(self.groupBox_2)
        self.btnCancel.setObjectName(u"btnCancel")
        self.btnCancel.setGeometry(QRect(143, 138, 81, 51))
        self.btnCancel.setFont(font2)
        self.btnreset = QPushButton(self.groupBox_2)
        self.btnreset.setObjectName(u"btnreset")
        self.btnreset.setGeometry(QRect(58, 138, 81, 51))
        self.btnreset.setFont(font2)
        self.label_7 = QLabel(self.groupBox_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(76, 28, 201, 20))
        self.label_13 = QLabel(self.groupBox_2)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(4, 101, 131, 16))
        self.lnauctionRegTime = QLineEdit(self.groupBox_2)
        self.lnauctionRegTime.setObjectName(u"lnauctionRegTime")
        self.lnauctionRegTime.setGeometry(QRect(137, 99, 201, 22))
        self.BtnchromKill = QPushButton(self.groupBox_2)
        self.BtnchromKill.setObjectName(u"BtnchromKill")
        self.BtnchromKill.setGeometry(QRect(58, 192, 281, 41))
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(15, 398, 251, 171))
        self.groupBox_3.setFont(font2)
        self.lbResult = QLabel(self.groupBox_3)
        self.lbResult.setObjectName(u"lbResult")
        self.lbResult.setGeometry(QRect(8, 28, 211, 16))
        self.lbresultTime = QLabel(self.groupBox_3)
        self.lbresultTime.setObjectName(u"lbresultTime")
        self.lbresultTime.setGeometry(QRect(10, 74, 241, 16))
        self.lbsuccessfulPrice = QLabel(self.groupBox_3)
        self.lbsuccessfulPrice.setObjectName(u"lbsuccessfulPrice")
        self.lbsuccessfulPrice.setGeometry(QRect(9, 51, 221, 16))
        self.labclick_time = QLabel(self.groupBox_3)
        self.labclick_time.setObjectName(u"labclick_time")
        self.labclick_time.setGeometry(QRect(8, 100, 241, 16))
        self.laboptimum = QLabel(self.groupBox_3)
        self.laboptimum.setObjectName(u"laboptimum")
        self.laboptimum.setGeometry(QRect(8, 126, 241, 16))
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(61, 9, 521, 31))
        font4 = QFont()
        font4.setFamilies([u"HY\uacac\uace0\ub515"])
        font4.setPointSize(20)
        font4.setBold(False)
        self.label_9.setFont(font4)
        self.label_9.setAlignment(Qt.AlignCenter)
        self.groupBox_4 = QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(10, 579, 611, 321))
        self.groupBox_4.setFont(font2)
        self.listProgress = QListWidget(self.groupBox_4)
        self.listProgress.setObjectName(u"listProgress")
        self.listProgress.setGeometry(QRect(10, 20, 591, 291))
        self.groupBox_5 = QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(270, 115, 351, 81))
        font5 = QFont()
        font5.setFamilies([u"Agency FB"])
        font5.setPointSize(10)
        font5.setBold(True)
        self.groupBox_5.setFont(font5)
        self.label_5 = QLabel(self.groupBox_5)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(30, 20, 81, 21))
        self.label_6 = QLabel(self.groupBox_5)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(30, 50, 81, 21))
        self.linID = QLineEdit(self.groupBox_5)
        self.linID.setObjectName(u"linID")
        self.linID.setEnabled(True)
        self.linID.setGeometry(QRect(93, 22, 131, 22))
        self.linPW = QLineEdit(self.groupBox_5)
        self.linPW.setObjectName(u"linPW")
        self.linPW.setEnabled(True)
        self.linPW.setGeometry(QRect(94, 53, 131, 22))
        self.btnaccountReg = QPushButton(self.groupBox_5)
        self.btnaccountReg.setObjectName(u"btnaccountReg")
        self.btnaccountReg.setEnabled(True)
        self.btnaccountReg.setGeometry(QRect(244, 36, 91, 41))
        self.checRegMode = QCheckBox(self.groupBox_5)
        self.checRegMode.setObjectName(u"checRegMode")
        self.checRegMode.setEnabled(True)
        self.checRegMode.setGeometry(QRect(245, 15, 101, 16))
        font6 = QFont()
        font6.setPointSize(8)
        self.checRegMode.setFont(font6)
        self.groupBox_6 = QGroupBox(self.centralwidget)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(16, 213, 251, 171))
        self.groupBox_6.setFont(font1)
        self.label_8 = QLabel(self.groupBox_6)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(5, 45, 71, 21))
        self.linfixedPrice = QLineEdit(self.groupBox_6)
        self.linfixedPrice.setObjectName(u"linfixedPrice")
        self.linfixedPrice.setGeometry(QRect(74, 46, 91, 22))
        self.checkFixed = QCheckBox(self.groupBox_6)
        self.checkFixed.setObjectName(u"checkFixed")
        self.checkFixed.setGeometry(QRect(23, 22, 81, 16))
        self.label_10 = QLabel(self.groupBox_6)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(4, 72, 71, 21))
        self.linfixedPrice_2 = QLineEdit(self.groupBox_6)
        self.linfixedPrice_2.setObjectName(u"linfixedPrice_2")
        self.linfixedPrice_2.setGeometry(QRect(73, 73, 91, 22))
        self.label_11 = QLabel(self.groupBox_6)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(4, 99, 71, 21))
        self.linfixedPrice_3 = QLineEdit(self.groupBox_6)
        self.linfixedPrice_3.setObjectName(u"linfixedPrice_3")
        self.linfixedPrice_3.setGeometry(QRect(73, 100, 91, 22))
        self.linfixedPrice_4 = QLineEdit(self.groupBox_6)
        self.linfixedPrice_4.setObjectName(u"linfixedPrice_4")
        self.linfixedPrice_4.setGeometry(QRect(74, 128, 91, 22))
        self.label_12 = QLabel(self.groupBox_6)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(5, 127, 71, 21))
        self.range1 = QLineEdit(self.groupBox_6)
        self.range1.setObjectName(u"range1")
        self.range1.setGeometry(QRect(166, 73, 21, 22))
        self.range2 = QLineEdit(self.groupBox_6)
        self.range2.setObjectName(u"range2")
        self.range2.setGeometry(QRect(166, 100, 21, 22))
        self.range3 = QLineEdit(self.groupBox_6)
        self.range3.setObjectName(u"range3")
        self.range3.setGeometry(QRect(166, 128, 21, 22))
        self.label = QLabel(self.groupBox_6)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(188, 77, 21, 16))
        self.label_14 = QLabel(self.groupBox_6)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(188, 104, 21, 16))
        self.label_15 = QLabel(self.groupBox_6)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(188, 130, 21, 16))
        self.btncalcul = QPushButton(self.groupBox_6)
        self.btncalcul.setObjectName(u"btncalcul")
        self.btncalcul.setGeometry(QRect(170, 18, 81, 51))
        self.clickTime1 = QLineEdit(self.groupBox_6)
        self.clickTime1.setObjectName(u"clickTime1")
        self.clickTime1.setGeometry(QRect(199, 74, 51, 22))
        self.clickTime2 = QLineEdit(self.groupBox_6)
        self.clickTime2.setObjectName(u"clickTime2")
        self.clickTime2.setGeometry(QRect(200, 100, 51, 22))
        self.clickTime3 = QLineEdit(self.groupBox_6)
        self.clickTime3.setObjectName(u"clickTime3")
        self.clickTime3.setGeometry(QRect(200, 128, 51, 22))
        self.groupBox_7 = QGroupBox(self.centralwidget)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(270, 194, 351, 121))
        self.groupBox_7.setFont(font5)
        self.listAccount = QListWidget(self.groupBox_7)
        self.listAccount.setObjectName(u"listAccount")
        self.listAccount.setEnabled(True)
        self.listAccount.setGeometry(QRect(10, 20, 331, 91))
        self.lbTitle = QLabel(self.centralwidget)
        self.lbTitle.setObjectName(u"lbTitle")
        self.lbTitle.setGeometry(QRect(14, 86, 591, 20))
        self.lbTitle.setFont(font)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"\uc625\uc158", None))
        self.lbUrl.setText(QCoreApplication.translate("MainWindow", u"\uc785\ucc30 URL :", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"\uc785\ucc30 \uae08\uc561 \uc124\uc815", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\uae08\uc561 \ud55c\ub3c4 : ", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\ucd94\uac00 \uae08\uc561 :", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"\ucd08 \uc124\uc815", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\ub9c8\uac10\uc2dc\uac04 :", None))
        self.oneWindow.setText(QCoreApplication.translate("MainWindow", u"23-09-19 15:59:58.510", None))
        self.btnStart.setText(QCoreApplication.translate("MainWindow", u"\uc785 \ucc30 \uc2dc \uc791", None))
        self.btnCancel.setText(QCoreApplication.translate("MainWindow", u"\ucde8 \uc18c", None))
        self.btnreset.setText(QCoreApplication.translate("MainWindow", u"\uc7ac \uc124 \uc815", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u" Ex ) 23-09-19 15:59:58.510", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"\uc625\uc158 \uc785\ucc30\ub4f1\ub85d \uc2dc\uac04 :", None))
        self.BtnchromKill.setText(QCoreApplication.translate("MainWindow", u"ALL Chrom Kill", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"\uc785\ucc30 \uacb0\uacfc", None))
        self.lbResult.setText(QCoreApplication.translate("MainWindow", u"\uacb0 \uacfc :", None))
        self.lbresultTime.setText(QCoreApplication.translate("MainWindow", u"PC \uc785\ucc30 \ud074\ub9ad \uc2dc\uac04 :", None))
        self.lbsuccessfulPrice.setText(QCoreApplication.translate("MainWindow", u"\ub099\ucc30 \uae08\uc561 :", None))
        self.labclick_time.setText(QCoreApplication.translate("MainWindow", u"\uc785\ucc30 \ud074\ub9ad \uc815\ubcf4\ud1b5\uc2e0 \uc2dc\uac04 :", None))
        self.laboptimum.setText(QCoreApplication.translate("MainWindow", u"\ub124\ud2b8\uc6cc\ud06c \uc804\uccb4 \uc9c0\uc5f0\uc2dc\uac04 : ", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"\uc625\uc158 \uc785\ucc30 \ud504\ub85c\uadf8\ub7a8", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"\uc9c4\ud589 \uc0c1\ud669", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"\ub85c\uadf8\uc778", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\uc544\uc774\ub514    :", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\ube44\ubc00\ubc88\ud638:", None))
        self.btnaccountReg.setText(QCoreApplication.translate("MainWindow", u"\uacc4\uc815 \ub4f1\ub85d", None))
        self.checRegMode.setText(QCoreApplication.translate("MainWindow", u"\uacc4\uc815 \ub4f1\ub85d \ubaa8\ub4dc", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"\uace0\uc815 \uc785\ucc30", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"\uc785\ucc30 \uae08\uc5611", None))
        self.checkFixed.setText(QCoreApplication.translate("MainWindow", u"\uace0\uc815\uc785\ucc30", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"\uc785\ucc30 \uae08\uc5612", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"\uc785\ucc30 \uae08\uc5613 ", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"\uc785\ucc30 \uae08\uc5614 ", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.btncalcul.setText(QCoreApplication.translate("MainWindow", u"\uacc4\uc0b0", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("MainWindow", u"\uacc4\uc815 \ubaa9\ub85d", None))
        self.lbTitle.setText(QCoreApplication.translate("MainWindow", u"\uc785\ucc30 \uc81c\ubaa9  :", None))
    # retranslateUi

